// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmG7_Nevt0nFmjYaHMBgwvJrCyMaUP2uU',
    appId: '1:635831172336:web:80a78a6f5c58df5b66d635',
    messagingSenderId: '635831172336',
    projectId: 'climate-change-1aa43',
    authDomain: 'climate-change-1aa43.firebaseapp.com',
    storageBucket: 'climate-change-1aa43.appspot.com',
    measurementId: 'G-BT395BSE3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOS2eDqVnfyBZ2JyoUcOP22DOj7Z_gKI',
    appId: '1:635831172336:android:7d8bb1c8b8b433c466d635',
    messagingSenderId: '635831172336',
    projectId: 'climate-change-1aa43',
    storageBucket: 'climate-change-1aa43.appspot.com',
  );
}
